---
name: CI

on:  # yamllint disable rule:truthy
  push:
    branches:
      - main
    tags:
      - "*.*.*"
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Bazel fetch
        run: bazel fetch //...

      - name: Bazel test
        run: bazel test //...
